export const membersData = [
  {
    email: "lisa@test.com",
    username: "lisa",
    gender: "female",
    dateOfBirth: "1986-07-22",
    name: "Lisa Harrison",
    created: "2020-06-24",
    lastActive: "2020-06-21",
    description:
      "Friendly and outdoorsy, I love long walks, photography, and discovering new coffee spots. Always up for a chat and meeting new people.",
    city: "Manchester",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/women/41.jpg",
  },
  {
    email: "karen@test.com",
    username: "karen",
    gender: "female",
    dateOfBirth: "1995-10-12",
    name: "Karen Miller",
    created: "2019-12-09",
    lastActive: "2020-05-06",
    description:
      "I work in digital marketing and spend my free time reading, cooking, and exploring local markets. Love meeting people with good humour.",
    city: "Brighton",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    email: "margo@test.com",
    username: "margo",
    gender: "female",
    dateOfBirth: "1989-01-24",
    name: "Margo Thompson",
    created: "2019-08-10",
    lastActive: "2020-05-12",
    description:
      "Designer by trade, traveller at heart. I enjoy art galleries, city breaks, and discovering hidden gems around the UK.",
    city: "Edinburgh",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/women/43.jpg",
  },
  {
    email: "lois@test.com",
    username: "lois",
    gender: "female",
    dateOfBirth: "1988-06-22",
    name: "Lois Bennett",
    created: "2019-04-24",
    lastActive: "2020-06-17",
    description:
      "Teacher, book lover, and part-time baker. I enjoy quiet evenings, good films, and spontaneous weekend trips.",
    city: "Cardiff",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    email: "ruthie@test.com",
    username: "ruthie",
    gender: "female",
    dateOfBirth: "1986-01-12",
    name: "Ruthie James",
    created: "2019-04-30",
    lastActive: "2020-06-21",
    description:
      "I love fitness, yoga, and anything that involves being outdoors. Always happy to meet new people and share good conversation.",
    city: "Bristol",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    email: "todd@test.com",
    username: "todd",
    gender: "male",
    dateOfBirth: "1980-02-07",
    name: "Todd Wilson",
    created: "2019-04-29",
    lastActive: "2020-05-16",
    description:
      "Tech enthusiast and amateur guitarist. I enjoy cycling, gaming, and discovering new craft beer spots.",
    city: "Leeds",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    email: "michael@test.com",
    username: "michael",
    gender: "male",
    dateOfBirth: "1997-04-09",
    name: "Michael Hughes",
    created: "2020-04-05",
    lastActive: "2020-06-23",
    description:
      "Student and part-time barista. I enjoy football, streaming games, and hanging out with friends.",
    city: "Liverpool",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/men/42.jpg",
  },
  {
    email: "daniel@test.com",
    username: "daniel",
    gender: "male",
    dateOfBirth: "1990-03-23",
    name: "Daniel Richards",
    created: "2020-03-14",
    lastActive: "2020-05-17",
    description:
      "I work in finance and spend weekends hiking, cooking, and exploring new restaurants. Big fan of live music.",
    city: "London",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    email: "robbie@test.com",
    username: "robbie",
    gender: "male",
    dateOfBirth: "1982-12-01",
    name: "Robbie Holt",
    created: "2019-01-28",
    lastActive: "2020-06-07",
    description:
      "Easy-going and sociable. I enjoy travelling, photography, and meeting people from different backgrounds.",
    city: "Dublin",
    country: "Ireland",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
  },
  {
    email: "flynn@test.com",
    username: "flynn",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "Flynn Mercer",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "Family-oriented, calm, and thoughtful. I enjoy gardening, DIY projects, and quiet evenings with good company.",
    city: "Birmingham",
    country: "United Kingdom",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
];
